<?php

namespace Codeception\Template;

use Symfony\Component\Console\Exception\RuntimeException;
use Symfony\Component\Yaml\Yaml;

/**
 * Template for the `codecept init` command.
 */
class Lumiere extends Wpbrowser {


	/** @var string filename for the dist .env */
	protected $distEnvFilename;


	/**
	 * Initializes the build commands.
	 *
	 * @param bool $interactive unused
	 */
	public function setup( $interactive = true ) {

		$this->say( "Bootstrapping Lumiere\n" );

		$this->createDirs();

		$installation_data = $this->gatherInstallationData();

		$this->createEnvFiles( $installation_data );

		$this->loadEnvFile();

		$this->createGlobalConfig();

		$this->createIntegrationSuite( 'Integration' );

		$this->createAcceptanceSuite( 'Acceptance', $installation_data );

		$this->saySuccess( 'You did it!' );

		// TODO: lots more info to add here.
	}


	/**
	 * Gather installation data via CLI prompts.
	 *
	 * @return array
	 */
	protected function gatherInstallationData() : array {

		$installation_data = [];

		$wp_root = $this->ask(
			'Where is your test instance of WordPress installed?',
			'/var/www/wp'
		);

		$installation_data['WP_ROOT_FOLDER'] = $this->normalizePath( $wp_root );

		$wp_url = $this->ask(
			'What is the URL of the test site?',
			'https://wp.test'
		);

		$installation_data['WP_URL']    = $wp_url;
		$installation_data['WP_DOMAIN'] = str_replace( [ 'https://', 'http://' ], '', $wp_url );

		$installation_data['WP_ADMIN_PATH'] = '/wp-admin';

		$installation_data['WP_ADMIN_EMAIL'] = $this->ask(
			'What is the email address for your admin user?',
			'admin@wp.test'
		);

		$installation_data['WP_ADMIN_USERNAME'] = $this->ask(
			'What is the username for your admin user?',
			'admin'
		);

		$installation_data['WP_ADMIN_PASSWORD'] = $this->ask(
			'What is the password for your admin user?',
			'admin'
		);

		$installation_data['ACCEPTANCE_DB_NAME'] = $this->ask(
			'What is the name of the database you\'ll use for acceptance tests?',
			'acceptance_tests'
		);

		$installation_data['ACCEPTANCE_DB_HOST'] = $this->ask(
			'What is the host of the database you\'ll use for acceptance tests?',
			'localhost'
		);

		$installation_data['ACCEPTANCE_DB_USER'] = $this->ask(
			'What is the username for the database you\'ll use for acceptance tests?',
			'root'
		);

		$installation_data['ACCEPTANCE_DB_PASSWORD'] = $this->ask(
			'What is the username for the database you\'ll use for acceptance tests?',
			'root'
		);

		$installation_data['ACCEPTANCE_TABLE_PREFIX'] = $this->ask(
			'What is the table prefix for the database you\'ll use for acceptance tests?',
			'wp_'
		);

		$installation_data['INTEGRATION_DB_NAME'] = $this->ask(
			'What is the name of the database you\'ll use for integration tests?',
			'integration_tests'
		);

		$installation_data['INTEGRATION_DB_HOST'] = $this->ask(
			'What is the host of the database you\'ll use for integration tests?',
			'localhost'
		);

		$installation_data['INTEGRATION_DB_USER'] = $this->ask(
			'What is the username for the database you\'ll use for integration tests?',
			'root'
		);

		$installation_data['INTEGRATION_DB_PASSWORD'] = $this->ask(
			'What is the username for the database you\'ll use for integration tests?',
			'root'
		);

		$installation_data['INTEGRATION_TABLE_PREFIX'] = $this->ask(
			'What is the table prefix for the database you\'ll use for integration tests?',
			'wp_'
		);

		$plugin_name      = $this->ask( 'What is the name of the plugin?' );
		$plugin_directory = $this->ask( 'What is the plugin root directory when installed in WordPress?', basename( getcwd() ) );
		$plugin_file      = $this->ask( 'What is the main filename for the plugin?', "{$plugin_directory}.php" );

		$installation_data['plugin'] = [
			'name'      => $plugin_name,
			'directory' => $plugin_directory,
			'filename'  => $plugin_file,
		];

		$installation_data['other_plugins'] = [];

		$woocommerce = $this->ask( 'Does the plugin require WooCommerce?', 'yes' );
		$woocommerce = preg_match( '/^(n|N)/', $woocommerce ) ? false : true;

		if ( $woocommerce ) {
			$installation_data['other_plugins'][] = 'woocommerce/woocommerce.php';
		}

		// TODO: ask about other plugins?
		// TODO: ask about the framework? Install basic FW tests

		return $installation_data;
	}


	/**
	 * Creates the necessary .env files
	 *
	 * @param array $installation_data installation data, generated by the CLI prompts
	 */
	protected function createEnvFiles( array $installation_data ) {

		// local config env file
		$this->envFileName = '.env.lumiere';

		$filename = $this->workDir . DIRECTORY_SEPARATOR . $this->envFileName;

		$this->writeEnvFile( $filename, $installation_data );

		if ( ! empty( $installation_data['plugin'] ) ) {

			$this->distEnvFilename = '.env.lumiere.dist';

			$data = [
				'PLUGIN_NAME'     => $installation_data['plugin']['name'],
				'PLUGIN_DIR'      => $installation_data['plugin']['directory'],
				'PLUGIN_FILENAME' => $installation_data['plugin']['filename'],
			];

			$filename = $this->workDir . DIRECTORY_SEPARATOR . $this->distEnvFilename;

			$this->writeEnvFile( $filename, $data );
		}
	}


	/**
	 * Writes an .env file.
	 *
	 * @param string $filename desired filename
	 * @param array $data data to write
	 */
	public function writeEnvFile( $filename, array $data ) {

		$lines = [];

		foreach ( $data as $key => $value ) {

			if ( \is_bool( $value ) ) {
				$value = $value ? 'true' : 'false';
			} elseif ( null === $value ) {
				$value = 'null';
			} elseif ( \is_string( $value ) ) {
				$value = '"' . trim( $value ) . '"';
			} else {
				continue;
			}

			$lines[] = "{$key}={$value}";
		}

		$contents = implode("\n", $lines);

		$written = file_put_contents( $filename, $contents );

		if ( ! $written ) {
			throw new RuntimeException("Could not write {$filename} file!");
		}
	}


	/**
	 * Creates the global codeception config files.
	 */
	public function createGlobalConfig() {

		// create codeception.dist.yml
		$config = [
			'extends' => 'vendor/skyverge/lumiere/configs/codeception.yml',
			'params' => [
				trim( $this->distEnvFilename ),
			],
		];

		$contents = Yaml::dump( $config, 4 );

		$this->createFile( 'codeception.dist.yml', $contents );

		// create codeception.yml
		$config = [
			'extensions' => [
				'enabled' => [
					\tad\WPBrowser\Extension\Symlinker::class,
				],
				'config' => [
					\tad\WPBrowser\Extension\Symlinker::class => [
						'mode' => 'plugin',
						'destination' => '%WP_ROOT_FOLDER%/wp-content/plugins/',
					],
				],
			],
			'params' => [
				trim( $this->envFileName ),
			],
		];

		$contents = Yaml::dump( $config, 4 );

		$this->createFile( 'codeception.yml', $contents );
	}


	/**
	 * Generates the integration test suite.
	 *
	 * @param string $actor actor name
	 */
	protected function createIntegrationSuite( string $actor = 'Integration' ) {

		$suiteConfig = <<<EOF
# Integration test suite configuration.

actor: {$actor}{$this->actorSuffix}
extends: "../vendor/skyverge/lumiere/configs/integration.suite.yml"
modules:
  enabled:
    - \Helper\Integration
EOF;

		$this->createSuite( 'integration', $actor, $suiteConfig );
	}


	/**
	 * Generates the acceptance test suite.
	 *
	 * @param string $actor actor name
	 * @param array $installation_data installation data, generated by CLI prompts
	 */
	protected function createAcceptanceSuite( $actor = 'Acceptance', array $installation_data = [] ) {

		$suiteConfig = <<<EOF
# Acceptance set suite configuration.

actor: {$actor}{$this->actorSuffix}
extends: "../vendor/skyverge/lumiere/configs/acceptance.suite.yml"
modules:
  enabled:
    - \Helper\Acceptance
EOF;

		$this->createSuite( 'acceptance', $actor, $suiteConfig );
	}


}
