# Codeception Test Suite Configuration
#
# Suite for admin acceptance tests.
#
# Performs tests in browser using the WPWebDriver.
# Uses WPDb to set up the initial database fixture.

modules:
  enabled:
  - WooCommerceDB
  - WooCommerceBrowser
  - WPLoader
  config:
    WooCommerceDB:
      dsn: 'mysql:host=%ACCEPTANCE_DB_HOST%;dbname=%ACCEPTANCE_DB_NAME%'
      user: '%ACCEPTANCE_DB_USER%'
      password: '%ACCEPTANCE_DB_PASSWORD%'
      dump: 'tests/_data/dump.sql'
      #import the dump before the tests; this means the test site database will be repopulated before the tests.
      populate: true
      # re-import the dump between tests; this means the test site database will be repopulated between the tests.
      cleanup: true
      waitlock: 0
      url: '%WP_URL%'
      urlReplacement: true #replace the hardcoded dump URL with the one above
      tablePrefix: '%ACCEPTANCE_TABLE_PREFIX%'
    WooCommerceBrowser:
      url: '%WP_URL%'
      adminUsername: '%WP_ADMIN_USERNAME%'
      adminPassword: '%WP_ADMIN_PASSWORD%'
      adminPath: '%WP_ADMIN_PATH%'
      browser: 'chrome'
      host: '%SELENIUM_HOST%'
      capabilities:
        acceptInsecureCerts: true
        enableVerboseLogging: true
        "chromeOptions":
          args: ["disable-dev-shm-usage", "no-sandbox", "disable-infobars", "disable-gpu"]
    WPLoader:
      loadOnly: true
      wpRootFolder: '%WP_ROOT_FOLDER%'
      dbName: "%ACCEPTANCE_DB_NAME%"
      dbHost: "%ACCEPTANCE_DB_HOST%"
      dbUser: "%ACCEPTANCE_DB_USER%"
      dbPassword: "%ACCEPTANCE_DB_PASSWORD%"
