# Codeception Test Suite Configuration
#
# Suite for integration tests that require WordPress/WooCommerce functions and classes.

modules:
  enabled:
  - WPLoader
  config:
    WPLoader:
      wpRootFolder: "%WP_ROOT_FOLDER%"
      dbName: "%INTEGRATION_DB_NAME%"
      dbHost: "%INTEGRATION_DB_HOST%"
      dbUser: "%INTEGRATION_DB_USER%"
      dbPassword: "%INTEGRATION_DB_PASSWORD%"
      tablePrefix: "%INTEGRATION_TABLE_PREFIX%"
      domain: "%WP_DOMAIN%"
      adminEmail: "%WP_ADMIN_EMAIL%"
      title: "%PLUGIN_NAME% Integration Tests"
      plugins: ['woocommerce/woocommerce.php', '%PLUGIN_DIR%/%PLUGIN_FILENAME%']
      activatePlugins: ['woocommerce/woocommerce.php', '%PLUGIN_DIR%/%PLUGIN_FILENAME%']
